### ISSUE TITLE
use the volumes first time, then error!

### ISSUE THREAD

**Issue by witer5** [MaksymBilenko/docker-oracle-ee-11g#1]
oracle-ee: 
  image: sath89/oracle-ee-11g
  environment:
    - DBCA_TOTAL_MEMORY=1024
  volumes:
    - c:/Users/witer/Documents/db/a2:/u01/app/oracle
    #- c:/Intel/aaa223:/docker-entrypoint-initdb.d
 #   - c:/Intel/:/u01/app/oracle/oradata
  ports:
    - "8080:8080"
    - "1521:1521"

i docker-compose it up, and then :

Check /u01/app/oracle/product/11.2.0/EE/install/root_a240d3c75b24_2017-09-04_10-41-34.log for the output of root script
found files in /u01/app/oracle/oradata Using them instead of initial database
ORA-01078: failure in processing system parameters

![image](https://user-images.githubusercontent.com/4241120/30023739-427cd4e4-91a3-11e7-91ba-75bb2c899de8.png)

**Comment by MaksymBilenko** [comment]
@witer5 there are an issues related to windows and NTFS/FAT volumes and docker.

If you are running oracle database on wondows host - you cannot mount database files to the host filesystem.

I suggest you to use docker volumes.

Instead of path like `c:\...` you should use volume names without path `my_oracle_11g-ee:/u01/...`

That would store your database files with proper permissions inside of docker VM.

**Comment by witer5** [comment]
thank u.  i will have a test on it
